export const projectList = [
	{
		name: "Proyecto 1",
		technologies: ["react", "node"],
		description: "lorem ipsum dolor sit amet, consectetur adip",
		code: "",
		seeProject: "",
		img: "/proy7.webp",
		id: 0,
		position: 0,
	},
	{
		name: "Proyecto 2",
		technologies: ["react", "node"],
		description: "lorem ipsum dolor sit amet, consectetur adip",
		code: "a",
		seeProject: "a",
		img: "/proy6.webp",
		id: 1,
		position: 1,
	},
	{
		name: "Proyecto 3",
		technologies: ["react", "node"],
		description: "lorem ipsum dolor sit amet, consectetur adip",
		code: "a",
		seeProject: "a",
		img: "/proy4.webp",
		id: 2,
		position: 2,
	},
	{
		name: "Proyecto 4",
		technologies: ["react", "node"],
		description: "lorem ipsum dolor sit amet, consectetur adip",
		code: "a",
		seeProject: "a",
		img: "/proy8.webp",
		id: 3,
		position: 3,
	},
];
